#!/bin/bash

TAPDEV="tap0"
BRIDGEDEV="br0"
ETHDEV="enp0s3"

ip address delete 192.168.56.101/24 dev ${BRIDGEDEV}
ip address add 192.168.56.101/24 dev ${ETHDEV}
ip route add default via 192.168.56.0/24 dev ${ETHDEV}

sysctl net.ipv4.ip_forward=0
ip link delete ${BRIDGEDEV} up
ip addr del 10.0.0.1/24 dev br0
brctl delif ${BRIDGEDEV} ${TAPDEV}
tunctl -d ${TAPDEV}
ip link delete ${TAPDEV}
brctl delif ${BRIDGEDEV} ${ETHDEV}
ifconfig ${BRIDGEDEV} down
brctl delbr ${BRIDGEDEV}
#ifconfig ${ETHDEV} up
#dhclient -v ${ETHDEV}

#pkill dnsmasq
systemctl stop isc-dhcp-server
systemctl start NetworkManager
